name: Continuous Integration

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Run lint
        run: pnpm run lint

      - name: Run format check
        run: pnpm run format

      - name: Run type check
        run: pnpm run typecheck
